# Домашнее задание №5

### Задание №1 (1,5 балла)

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29.

In [1]:
import numpy as np

In [2]:
A = np.array([2, 4, 6, 8, 10, 12])
B = np.array([7, 11, 15, 18, 23, 29])
A

array([ 2,  4,  6,  8, 10, 12])

$1.$ Сложите массивы и возведите элементы получившегося массива в квадрат:

In [3]:
(A+B)**2

array([  81,  225,  441,  676, 1089, 1681], dtype=int32)

$2.$ Выведите все элементы из первого массива, которые стоят на тех местах, где элементы второго массива больше 12 и дают остаток 3 при делении на 5.

In [4]:
B[B>12]
A[np.arange(B.shape[0])%5==3]

array([8])

*3.* Для первого массива найдите остатки от деления на 2, а для второго --- на 3. Для каждого получившегося массива выведите его уникальные значения (см. семинар).

In [5]:
np.unique(A%2)

array([0], dtype=int32)

In [6]:
np.unique(B%3)

array([0, 1, 2], dtype=int32)

### Задание №2 (1,5 балла)

Найдите интересный для вас датасет. Например, можно выбрать датасет [тут](http://data.un.org/Explorer.aspx) или [тут](https://hls.harvard.edu/library/research/find-a-database/). Если выскакивают ошибки при считывании таблицы, попробуйте их погуглить и решить проблему!

1. Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
2. Проанализируйте и прокомментируйте содержательно получившиеся результаты
    - недостаточно написать фразы формата "Средний возраст = 60, а минимальный = 20", следует дать пояснение, что это значит и какие выводы можно сделать в рамках датасета
3. Все комментарии оформляйте строго в ячейках формата Markdown
    - для этого надо в выпадающем окошке сверху для текущей ячейки сменить тип Code на Markdown
    ![](https://i.imgur.com/vl7Fmg9.png)

In [7]:
dataset = np.loadtxt("1.txt", dtype=int)

In [8]:
dataset

array([[ 100,    1,   10, 1000],
       [ 200,    2,   20, 2000],
       [ 300,    3,   30, 3000],
       [ 400,    4,   40, 4000],
       [ 500,    5,   50, 5000],
       [ 600,    6,   60, 6000],
       [ 700,    7,   70, 7000],
       [ 800,    8,   80, 8000],
       [ 900,    9,   90, 9000]])

#### Среднее значение:

In [9]:
np.mean(dataset[:, 1])

5.0

#### Медиана:

In [10]:
np.median(dataset[:, 2])

50.0

#### Размах:

In [11]:
np.max(dataset[:, 0])-np.min(dataset[:, 0])

800

#### Дисперсия:

In [12]:
np.var(dataset[:, 3])

6666666.666666667